name: Update changelog
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
